/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'diegoalves' at '24/02/16 00:12' with Gradle 2.4
 *
 * @author diegoalves, @date 24/02/16 00:12
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
